############### TASK ###############

### Post tasks (create)
POST {{baseUrl}}/{{version}}/tasks
Accept: */*
content-type: application/json
Authorization: Bearer {{ user_jwt_token }}

{
    "description": "Be someone else"
}

### GET tasks (all)
GET {{baseUrl}}/{{version}}/tasks
Accept: */*
content-type: application/json
Authorization: Bearer {{ user_jwt_token }}

### GET tasks (one)
GET {{baseUrl}}/{{version}}/tasks/5eac2a64c6e65421b74fda5c
Accept: */*
content-type: application/json

### PATCH tasks (update)
PATCH {{baseUrl}}/{{version}}/tasks/5eb0957b8003321aa50baa76
Accept: */*
content-type: application/json
Authorization: Bearer {{ user_jwt_token }}

{
    "completed": false
}

### Delete tasks (destroy)
DELETE {{baseUrl}}/{{version}}/tasks/5eb0957b8003321aa50baa76
Accept: */*
content-type: application/json
Authorization: Bearer {{ user_jwt_token }}

{
    "restore": true
}