############### USER ###############

### GET users (all)
GET {{baseUrl}}/{{version}}/users
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_JWT_TOKEN }}

### GET user (one)
GET {{baseUrl}}/{{version}}/users/52
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_JWT_TOKEN }}

### GET user (profile)
GET {{baseUrl}}/{{version}}/users/profile
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_JWT_TOKEN }}

### POST users (create)
POST {{baseUrl}}/{{version}}/users
Accept: */*
content-type: application/json

{
    "email": "user39@email.com",
    "admin": false
}

### PATCH users (update)
PATCH {{baseUrl}}/{{version}}/users/51
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv USER_JWT_TOKEN }}

{
    "email": "emsssail3@gmail.com",
    "password": "susper@Difsficultpasssw00rd"
}

### Delete users (destroy)
DELETE {{baseUrl}}/{{version}}/users/10
Accept: */*
content-type: application/json
Authorization: Bearer {{ $dotenv ADMIN_JWT_TOKEN }}